### ISSUE TITLE
Erro na geração dos campos de variável leg()

### ISSUE THREAD

**Issue by CarolinaVanuchi** [Joao-Peterson/Math2Tex#1]
O problema ocorreu quando uma variável com subscrito foi compilada como uma legenda com o nome da variável mais outra legenda com o nome do subscrito, quando na verdade deveriam ser uma.
![image](https://user-images.githubusercontent.com/18645485/85306224-8ea3be80-b484-11ea-8fda-64368a4e72ff.png)

```
[Complete] - done - line 1 - Arquivo worskheet.xml lido com sucesso
Expressao [0]: text(para("⨌Para o circuito apresentado na Figura 1, foi solicitado a determinação de uma expressão que relaciona a tensão de saída V","⨌o, com as tensões de entrada V1 e V2, a seguir é apresentado o circuito mencinado.")) - Tipo: text
Expressao [1]: img("Questao_1_images/img0.png") - Tipo: image
Expressao [2]: text(para("⨌A análise desse circuito será realizada em duas partes, sendo a primeira até o ponto Vs e a segunda até o ponto Vo, dessa forma na Figura 2, será apresentado o circuito para primeira análise.")) - Tipo: text
Expressao [3]: img("Questao_1_images/img1.png") - Tipo: image
Expressao [4]: text(para("⨌Realizando o somatório das correntes no ponto Va, é obtida a equação 1, desecrita a seguir.")) - Tipo: text
Expressao [5]: equal(sub(add(leg("i","","")leg("1","",""),leg("i","","")leg("2","","")),leg("i","","")leg("3","","")),"0") - Tipo: math
[LUA] ERROR: [string "add_field(equal(sub(add(leg("i","","")leg("1"..."]:1: ')' expected near 'leg'

```

**Comment by Joao-Peterson** [comment]
Resolvido, era um problema na leitura de tags, um prefixo do tipo <pw:tag> imprevisto atrapalhou a interpretação. Também ressaltou erros na geração de legendas, quando apenas um argumento estava presente a interpretação era do tipo: leg("K"," "," "), e quando havia mais de um argumento era: leg("K","1",""), a string vazia gerava problemas com o script lua. Obrigado pelo tópico.
