### ISSUE TITLE
Símbolo de percentual

### ISSUE THREAD

**Issue by Libianno** [Joao-Peterson/Math2Tex#4]
Rodei o programa um arquivo Mathcad meu e ele n retornou nada, quando tirei o símbolo de percentual consegui que gerasse um arquivo porem nada foi gerado depois do ponto em que existia o percentual.  vou enviar em anexo o arquivo original, o log do mesmo, o arquivo modificado e o arquivo .tex gerado.
[a enviar.zip](https://github.com/Joao-Peterson/Math2Tex/files/5505938/a.enviar.zip)

**Comment by Joao-Peterson** [comment]
Caro colega, realmente, atualmente não incluí suporte para o simbolo percentual, o código no momento está procurando por nomes de tags individualmente e falhando quando uma nova tag é encontrada, neste caso <percent>, que é a tag para o simbolo de porcentagem. Devido a natureza do programa ser de falhar nestes casos eu estou reescrevendo o código do zero, no meio tempo antes da próxima versão eu peço para que você não utilize o simbolo por hora e deverá assim conseguir utilizar o programa. Quanto a segunda vez que tu rodastes o programa eu creio que você possa ter colocado o nome do arquivo modificado "zenermod.mcdx" de forma errada, peço que delete os arquivos residuais do processo e rode novamente o programa com atenção ao nome do arquivo. De antemão também alerto sobre o uso de imagens, presentes na sua folha mathcad, utilize a opção de inclusão de imagens mas lembre que este necessita de uma cópia do seu arquivo salvo em .rtf. Abraço e até o próximo commit.

**Comment by Libianno** [comment]
Bom dia João, obrigado por responder.
Fiz o que vc disse: criei uma nova pasta sem arquivos preexistentes, coloquei uma nova versão do arquivo dessa vez sem imagem, adicionei os 3 arquivos necessários e rodei novamente seu programa.
Ainda assim o arquivo .tex não passa daquela linha, me certifiquei de rodar com o nome correto do arquivo. Vou enviar todos os arquivos em anexo. 
Obrigado pelo projeto incrível !!  
Abraço.
[zenermod2.zip](https://github.com/Joao-Peterson/Math2Tex/files/5510115/zenermod2.zip)

**Comment by Joao-Peterson** [comment]
Olá, pessoalmente eu não utilizo as unidades de medidas fornecidas pelo mathcad, utilizo apenas os numeros, quando é realizada uma avaliação numérica, operador "=", e esse resultado é alterado, como no seu caso, de "A" para "mA", ou ainda um expoente "10^3" o programa não consegue identificar esse resultado numérico, justamente por eu não antecipar o uso de unidades de medida. Assim, eu peço que não as utilize e talvez as inclua diretamente no .tex gerado, também de antemão lhe peço para tomar cuidado com o operador de avaliação numérica, pois as vezes o resultado irá aparecer como "0.000", outro bug conhecido que será consertado na próxima versão. Segue um zip com as alterações que realizei para fazer funcionar. Obrigado pelo apoio e paciência.
[modified.zip](https://github.com/Joao-Peterson/Math2Tex/files/5510364/modified.zip)

**Comment by Libianno** [comment]
Bom dia, obrigado pela atenção. Vi sua versão arquivo e vou tentar utilizar dessa forma. Ansioso pelas próximas atualizações.
